name = "HTMLStrings"
uuid = "c47fe496-5789-4377-b1db-55e89f2ee0c6"
authors = ["Dale Black <djblack@uci.edu> and contributors"]
version = "0.1.1"

[deps]

[compat]
Aqua = "0.7.4"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
